services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_REPO}:${VERSION}
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev